### ISSUE TITLE
Some character display in markdown is wrong

### ISSUE THREAD

**Issue by darkz1984** [yuki-kimoto/gitprep#100]
In the markdown document,such 
<pre>
a_b
</pre>
may by display as ab

and 
<pre>
*.*
</pre>
will dispaly as . without *
May be it is the problem with mardown render engine?

**Comment by yuki-kimoto** [comment]
I support foo_bar_baz at master.

About after one, you should escape 

    \*.\*

**Comment by darkz1984** [comment]
@yuki-kimoto  Yes,I can use this method to reslove this problem,but in other markdown editor,is not needs to do like this.
And Because the concent block is in <pre></pre>,so I think it should keep as what it is ,not use it like \*.\*

**Comment by yuki-kimoto** [comment]
Test

*.*

    *.*

a_b

    a_b

**Comment by yuki-kimoto** [comment]
@darkz1984 

I tried GitPrep markdown.
In code block, \*.\* is \*.\*

Outer code block, \*.\* become .

**Comment by yuki-kimoto** [comment]
test

**Comment by darkz1984** [comment]
I use 2.3,and it seems be ok
