### ISSUE TITLE
SQLite fails with "file is encrypted or is not a database" when doing a search

### ISSUE THREAD

**Issue by minoken** [yuki-kimoto/gitprep#101]
I want to upgrade from v1.12 to 2.2.1.

I try to this command(backup and copy db from old to new).
`mv gitprep gitprep.1.12`
`mv gitprep.1.12/data/gitprep.db gitprep.1.12/data/gitprep_v1bak.db`
`mv gitprep-latest gitprep`
`cd gitprep`
`./setup_module`
`prove t`
`./setup_database old/copy_database_v1_to_v2 ../gitprep.1.12/data/gitprep_v1bak.db data/gitprep.db`

But I see this error in production log.
`Can't create user table properly: DBD::SQLite::db prepare failed: file is encrypted or is not a database.` `Following SQL is executed.`
`select row_id, id, admin, password, salt, email, name from "user"  `
`(DBIx::Custom::_create_query) at ./setup_database line 65.`

Please help me.

**Comment by yuki-kimoto** [comment]
That maybe DBD::SQLite error.

At first. The following line should be tow lines.
    
    # Wrong
    ./setup_database old/copy_database_v1_to_v2 ../gitprep.1.12/data/gitprep_v1bak.db data/gitprep.db

    # Right
     ./setup_database
    old/copy_database_v1_to_v2 ../gitprep.1.12/data/gitprep_v1bak.db data/gitprep.db 

And tell me more information.

Your perl version. Do you use perlbrew? Do you upgrade Perl?

**Comment by minoken** [comment]
Thanks for reply.

My perl version is 5.16.3. I used perlbrew.
I succeeded updating by the following line!
```
# Right
./setup_database
old/copy_database_v1_to_v2 ../gitprep.1.12/data/gitprep_v1bak.db data/gitprep.db
```

thank you!

**Comment by yuki-kimoto** [comment]
You are welcome.
