### ISSUE TITLE
Update from v1.10 to v2.2.1 fails

### ISSUE THREAD

**Issue by flixh** [yuki-kimoto/gitprep#103]
Hi,

I'm having two problems updating from an old v1.10 installation to v2.2.1 (or current head):

i) The database upgrade fails with the following message:
```
~/gitprep$ old/copy_database_v1_to_v2 data/gitprep_v1bak.db data/gitprep.db
DBD::SQLite::st execute failed: UNIQUE constraint failed: collaboration.project, collaboration.user. Following SQL is executed.
 insert into "collaboration" ("project", "row_id", "user") values (? , ? , ? ) 
(DBIx::Custom::execute) at old/copy_database_v1_to_v2 line 196.
```
ii) I can't test if that failure is fatal as I can't connect to the newly started gitprep instance. The production.log tells me:
```
[Fri Jul 29 15:09:16 2016] [error] Event "read" failed: Can't locate object method "auto_decompress" via package "Mojo::Content::Single" at /home/gitprep/gitprep/script/../lib/Gitprep.pm line 555.
```

Any ideas?
Regards
Felix

**Comment by yuki-kimoto** [comment]
This is not upgrading problem.

See and fix collaboration table.

https://github.com/yuki-kimoto/gitprep#i-cant-add-more-than-one-collaborator

**Comment by flixh** [comment]
Thanks for the hint.
I tried that earlier as well and upgrading failed nevertheless, but I must have forgotten to restart (the old) gitprep after dropping the collab table. Done that now and the subsequent update worked fine.
Thanks,
Felix
