### ISSUE TITLE
Url is wrong when I logout

### ISSUE THREAD

**Issue by darkz1984** [yuki-kimoto/gitprep#104]
I setup git on my server and use http://git.xxx.xx. 
But when I logout in gitprep, the url is https://git.xxx.xx. 
The https  is another site...

**Comment by yuki-kimoto** [comment]
OK. I will check it.

**Comment by darkz1984** [comment]
I change the nginx proxy,
from
>proxy_set_header X-Forwarded-HTTPS "on";
to
>proxy_set_header X-Forwarded-Proto "https";

and the https problem is OK
