### ISSUE TITLE
Pull request does not work

### ISSUE THREAD

**Issue by helmithejoe** [yuki-kimoto/gitprep#111]
I tried to fork some repo, doing changes and push in my fork and then make a pull request to the original repo which i forked from, but it says : "There isn't anything to compare."

And when i tried to make pull request from my own repo page (not the one i forked from) the editor page appeared but when i submit, it says : we,re sorry. something went very wrong .

This is the production.log : 
[Thu Aug 18 09:06:16 2016] [error] DBD::SQLite::st execute failed: UNIQUE constraint faile                         d: pull_request.base_project, pull_request.base_branch, pull_request.target_project, pull_                         request.target_branch. Following SQL is executed.
 insert into "pull_request" ("base_branch", "base_project", "target_branch", "target_proje                         ct") values (? , ? , ? , ? )
(DBIx::Custom::execute) at template /compare.html.ep line 113.
161:     # Icky backwards compatibility wrapper. :-(
162:     local @CARP_NOT = $cgc ? $cgc->() : caller();
163:     shortmess_heavy(@_);
164: }
165:
166: sub croak   { die shortmess @_ }
167: sub confess { die longmess @_ }
168: sub carp    { warn shortmess @_ }
169: sub cluck   { warn longmess @_ }
170:
171: BEGIN {

**Comment by helmithejoe** [comment]
This is the production.log :+1: 
[Thu Aug 18 09:06:16 2016] [error] DBD::SQLite::st execute failed: UNIQUE constraint faile                         d: pull_request.base_project, pull_request.base_branch, pull_request.target_project, pull_                         request.target_branch. Following SQL is executed.
 insert into "pull_request" ("base_branch", "base_project", "target_branch", "target_proje                         ct") values (? , ? , ? , ? )
(DBIx::Custom::execute) at template /compare.html.ep line 113.
161:     # Icky backwards compatibility wrapper. :-(
162:     local @CARP_NOT = $cgc ? $cgc->() : caller();
163:     shortmess_heavy(@_);
164: }
165:
166: sub croak   { die shortmess @_ }
167: sub confess { die longmess @_ }
168: sub carp    { warn shortmess @_ }
169: sub cluck   { warn longmess @_ }
170:
171: BEGIN {

**Comment by yuki-kimoto** [comment]
I will check that problem.

**Comment by yuki-kimoto** [comment]
I fixed now this bug at master.

**Comment by helmithejoe** [comment]
Hi Yuki,

i have tried your new fix just now. Here is my testing scenario 

1. I create 2 user : let's say A & B
2. User A create a public repo named TEST and doing first push to master branch
3. User B fork TEST repo, doing changes and push to his own TEST to master branch
4. User B tried to make a pull request with compare details as follow

base fork : A/TEST
base : master

head fork : B/TEST
compare : master

it says : "There isn't anything to compare."

But, when I change scenario number 3 and 4 to

3. User B fork TEST repo, doing changes and push to his own TEST to FEATURE branch (not master)
4. User B tried to make a pull request with compare details as follow

base fork : A/TEST
base : master

head fork : B/TEST
compare : feature

Then the result is page showing "raptor not found"

What do you think about my scenario? Is there any mistake about my workflow about doing the pull request?

I hope my scenario will help you to fix the problem.

**Comment by yuki-kimoto** [comment]
I will try this. Please wait for a while.

**Comment by yuki-kimoto** [comment]
I fixed this bug now. Let's try again.

**Comment by helmithejoe** [comment]
I have tried it again and pull request feature is working smoothly now. 

Anyway, I found another bug. When I have logged out. I still able to click the "pull request" button. And can cause this error if I submit the request:

[Sat Aug 20 12:12:55 2016] [error] DBD::SQLite::st execute failed: NOT NULL constraint failed: issue.open_user. Following SQL is executed.
 insert into "issue" ("number", "open", "open_time", "open_user", "project", "pull_request", "title") values (? , ? , ? , ? , ? , ? , ? )
(DBIx::Custom::execute) at template /compare.html.ep line 149.
95:     # Icky backwards compatibility wrapper. :-(
96:     local @CARP_NOT = $cgc ? $cgc->() : caller();
97:     shortmess_heavy(@_);
98: }
99:
100: sub croak   { die shortmess @_ }
101: sub confess { die longmess @_ }
102: sub carp    { warn shortmess @_ }
103: sub cluck   { warn longmess @_ }
104:
105: BEGIN {

I also found another small problem. When I want to create a pull request. The "view" button showing an error when I click it.

*The view button position is under the "Showing 1 changed files with 3 additions and 0 deletions" caption

here is the URL :
 
/test/blob/b5ada2c3fd1f15de6ad294c4cb6a159565903d92/README.md


And here is the production.log : 

[Sat Aug 20 12:32:14 2016] [error] Reading cat-file failed at template /blob.html.ep line 26.
95:     # Icky backwards compatibility wrapper. :-(
96:     local @CARP_NOT = $cgc ? $cgc->() : caller();
97:     shortmess_heavy(@_);
98: }
99:
100: sub croak   { die shortmess @_ }
101: sub confess { die longmess @_ }
102: sub carp    { warn shortmess @_ }
103: sub cluck   { warn longmess @_ }
104:
105: BEGIN {

**Comment by helmithejoe** [comment]
I create pull request to fix this. Please check it out.

https://github.com/yuki-kimoto/gitprep/pull/112

**Comment by yuki-kimoto** [comment]
Sorry, I fixed this bugs by myself just now.

**Comment by helmithejoe** [comment]
Yes, I would like to join in this project. This is an interesting project.

I only have some time. Maybe I'll do some bug fixing only. 
Anyway, my Perl knowledge is little now. Usually i'm working with PHP  ;-)

Btw, I have new changes in my fix#111 branch. You can check it out.

**Comment by helmithejoe** [comment]
Hi Yuki,.. I have test your fix and everything is ok now. So, I don't need to fix again for now. Thanks..
