### ISSUE TITLE
Another way to hide home user

### ISSUE THREAD

**Issue by CieNTi** [yuki-kimoto/gitprep#114]
First of all, thank you for this amazing application.

I read all your documentation, and "how to hide user home folder" works only if you have full access to server (I cannot create a `/git` in my shared server, as example), but I started to use a few ago a different URL to clone/use my repos:

```
ssh_user@server:gits_folder/gitprep_user/repo.git
```

I tried this and is working perfect:
1. Backup your data at `gitprep/data/rep`
2. Move `gitprep/data/rep` to `~/gits_folder`
3. Symbolink `ln -s ~/gits_folder gitprep/data/rep`
4. Edit `gitprep.conf` and set `ssh_rep_url_base=:gits_folder`

After this, you can access the repository as said before.

Do you see any incompatibilities/problems?

I hope you find this useful.

Best regards

**Comment by yuki-kimoto** [comment]
@CieNTi

I have a question. "1. Remove gitprep/data/rep". Is this right?

**Comment by yuki-kimoto** [comment]
Your way is better than the way written in README.md

I have rewritten README now.

**1. Use symbolic link and ssh_rep_url_base option**

At first, set [basic]ssh_rep_url_base option to /~/git

    ;;; SSH repository url base
    ; For exampke, If you set this value to /~/git, SSH repository url become
    ; ssh://gitprep@59.106.185.196/~/git/kimoto/gitprep.git
    ; ~ is exapned to user home directory automatically
    ssh_rep_url_base=/~/git

Next, you create symbolic link to /home/gitprep/gitprep/data/rep
    
    cd ~
    ln -s ~/gitprep/data/rep ~/git

**Comment by CieNTi** [comment]
Hi back!

Thanks for the reply and interest :)

First, yes about deleting "/rep" (obviously if you don't have it populated, I'll edit it after post this) because you will need this node for the new symbolic link.

And about the colon (:) part:

Is not only for port part, is the alternate scp-like form:

http://stackoverflow.com/questions/14348874/git-repository-url-ssh-syntax-without-absolute-path

https://git-scm.com/book/tr/v2/Git-on-the-Server-The-Protocols#The-SSH-Protocol

And appears too in the URL you gave, just a few lines below

> An alternative scp-like syntax may also be used with the ssh protocol:
> [user@]host.xz:path/to/repo.git/

(And my doubt here is "how to put a port in this form?", but is not my problem now because is a fixed 22TCP)

So if you create a folder on HOME, it's accesible as `user@host:folder_in_home` and, because you did things very right in my opinion, a symbolic link to this folder from `gitprep/data/rep` is not only possible, it works like a charm!!

**Comment by CieNTi** [comment]
First post edited with a better/safer method

**Comment by yuki-kimoto** [comment]
I red the link topic. You are right in URL.

In my opinion, You don't need to remove gitprep/data/rep by reversing symbolic link order.

    cd ~
     ln -s gitprep/data/rep ~/gits_folder

**Comment by CieNTi** [comment]
Totally agree. This comes because initially I was using gitlist and that was the repo folder, so my natural movement was that link direction and not the opposite.

I'll reverse it in my installation :)

Do you find `user@host:folder_in_home` better than using home or `user@host/~/folder_in_home` or do you see any other incompatibility/problem?

**Comment by yuki-kimoto** [comment]
user@host:folder_in_home is OK!

There is no incompatibility/problem.
