### ISSUE TITLE
Gravatar image

### ISSUE THREAD

**Issue by CieNTi** [yuki-kimoto/gitprep#115]
Hello,

Comparing my old gitlist installation against my brand new gitprep's one I realized there is no user image.

As in github, gitlist use gravatar image in this way:

``` html
<img src="https://gravatar.com/avatar/{{ commit.author.email | lower | md5 }}?s=32" class="pull-left space-right" />
```

After search for this twig's bit explanation I found it's just like `md5(to_lower_case(author_email))`.

NOTE: I just searched for this in the original repo but it's now a function ([gitlist repo twig template](https://github.com/klaussilveira/gitlist/blob/master/themes/bootstrap3/twig/commit.twig)), anyway the URL to include gravatar image is the same.

It's possible to you to add this feature?

Thanks in advance

**Comment by yuki-kimoto** [comment]
@CieNTi

I can add this feature. 

Do you have some time? How do you try to implement this feature?

If you don't understand GitPrep source code, I teach you.

**Comment by CieNTi** [comment]
I did perl a long ago, but I'll try.

Anyway, if you can send me some start point, i'll get it and eat  it :D

**Comment by CieNTi** [comment]
Check please:

http://git.cienti.com/gitprep_test/gitprep.cgi/CieNTi/test_repo/commits/master

This is the first approach, I understand there is a lot of places where avatar should appear, but I find my code like "stone-graved" and maybe it's better to set an "avatar" variable and fill it with user avatar or gravatar url

What do you think?

Diff: https://github.com/yuki-kimoto/gitprep/compare/master...CieNTi:master

**Comment by yuki-kimoto** [comment]
I try this.

**Comment by CieNTi** [comment]
Ok, tell me if you want I code/try/test something.

**Comment by yuki-kimoto** [comment]
Good.

If you want to use "avator" variable, you can add "avator" column to user table. This is done in "setup_database" script.

If you change the value, you can edit "templates/user-settings.html".

At first, how about adding user image in needed pages.

**Comment by Zero3K** [comment]
Any news regarding this issue?
