### ISSUE TITLE
Labels not generated for new repositories

### ISSUE THREAD

**Issue by socialmedialabs** [yuki-kimoto/gitprep#117]
Only the first repository has labels, the following repos don't have any. Is this meant to work that way? #

**Comment by socialmedialabs** [comment]
Ok, I think I found the culprit. In _/templates/issues.html.ep_ on **line 47** the query checks for any available labels, regardless if these labels belong to the particular project or not:

`my $labels_count = app->dbi->model('label')->select('count(*)')->value;`

Changing the query to the following fixes the problem:

`  my $labels_count = app->dbi->model('label')->select('count(*)',
        where => {'project.id' => $project_id})->value;`

Hope, this helps

**Comment by yuki-kimoto** [comment]
socialmedialabs

thank you.

a little wrong, the following is right.

    my $labels_count = app->dbi->model('label')->select('count(*)', where => {'user.id' => $user_id, 'project.id' => $project_id})->value;

If you do pull request, I can merge it.

**Comment by socialmedialabs** [comment]
@yuki-kimoto apologies for the late reply, I didn't get any notification about your answer here.

I have modified my repo as per your suggestion. Pull request should be up to date.

Arigatou gozaimasu

**Comment by yuki-kimoto** [comment]
@socialmedialabs

I merge request and fix some bugs.
