### ISSUE TITLE
ssh login name shows wrong

### ISSUE THREAD

**Issue by socialmedialabs** [yuki-kimoto/gitprep#118]
When creating a repository on the summary page as well as on the overview page of the project the ssh login name that's shown is wrong.

Example:

It shows
_ssh://**u1234567**@git.mydomain.com/mypath/gitprep/data/rep/username/_

while it should show
_ssh://**u-1234567-myname**@git.mydomain.com/mypath/gitprep/data/rep/username/_

So GitPrep somehow seems to fail in reading the correct ssh username.

I am on a shared hosting and in the above example _1234567_ is my account number, whereas my ssh login is a combination of a prefix (_u-_), my account number (_1234567_) and followed by a provided id for the specific ssh account (in the above example _myname_).

**Comment by yuki-kimoto** [comment]
I use execute user as ssh user.

```
  # tree.html.ep
  my $execute_user = getpwuid($>);
  my $ssh_rep_url_base = defined app->config->{basic}{'ssh_rep_url_base'}
    ? app->config->{basic}{'ssh_rep_url_base'} : $rep_home;
  my $ssh_rep_url = "ssh://$execute_user\@" . $url->host
    . ($ssh_port ? ":$ssh_port" : '') . "$ssh_rep_url_base/$user_id/$project_id.git";
```

I should create a option to change execute user.

**Comment by yuki-kimoto** [comment]
ssh_user option is added.

https://github.com/yuki-kimoto/gitprep/pull/220
