### ISSUE TITLE
Green colored header and footer

### ISSUE THREAD

**Issue by halilibrahim** [yuki-kimoto/gitprep#120]
Hi,
GitPrep style turned green after upgrade. Is this look ok or have i done something wrong while upgrading?

![gitprep](https://cloud.githubusercontent.com/assets/5882923/19675980/388897c6-9a9a-11e6-92f1-6f362ed7f1eb.png)

**Comment by socialmedialabs** [comment]
Reading the commit history would help ;) This was introduced in commit [1e5650efc6ead18a420bcedae07e79b4691df0e5](https://github.com/yuki-kimoto/gitprep/commit/1e5650efc6ead18a420bcedae07e79b4691df0e5)

**Comment by halilibrahim** [comment]
Yes you're right :)

**Comment by yuki-kimoto** [comment]
I'm redesign GitPrep theme color. I want to get origin design.
