### ISSUE TITLE
install on shared hosting failed

### ISSUE THREAD

**Issue by vdcrea** [yuki-kimoto/gitprep#121]
Hi, trying to install gitprep on 1&1 shared hosting failed. Perl v5.20.2

Here is the first failure message during `./setup_module`

```
  Building and testing IO-Socket-IP-0.38 ... FAIL
  ! Installing IO::Socket::IP failed. See /[...]/gitprep/setup/work/1477380615.11990/build.log for details. Retry with --force to force install it.
  ! Installing the dependencies failed: Installed version (0.29) of IO::Socket::IP is not in range '0.37'
  ! Bailing out the installation for Mojolicious-6.57.
  ! Installing the dependencies failed: Module 'Mojolicious' is not installed
  ! Bailing out the installation for Mojolicious-Plugin-INIConfig-0.03.
```
After that, all modules dependent on Mojolicious failed.  
Then `prove t` displays:

```
  t/age_string.t .. Can't locate Mojo/Base.pm in @INC (you may need to install the Mojo::Base module)
```

Any idea of how I can do to install GitPrep? If it s possible?
Cheers.

**Comment by yuki-kimoto** [comment]
@vdcrea 

Please show error log

    gitprep/setup/work/1477380615.11990/build.log

What error message you see?

**Comment by vdcrea** [comment]
About `Failed test 'IO::Socket::IP->new constructs a SOCK_STREAM socket'`:
Connection closed by set timeout (something like this but in french language ^^, then
`Can't call method "sockdomain" on an undefined value at t/04local-client-v6.t line 58.`

It seems like this error made mojolicious install fail.  
You can download [full log here](contact.vdcrea.com/build.log.zip)

**Comment by yuki-kimoto** [comment]
https://rt.cpan.org/Public/Bug/Display.html?id=104836

**Comment by yuki-kimoto** [comment]
You can try force-install.

    perl -Iextlib/lib/perl5 cpanm -f -L extlib IO::Socket::IP

**Comment by vdcrea** [comment]
Ok I "force-installed" IO::Socket::IP, then re `./setup_module`, I saw mojolicious installed correctly during the process.  
Now GitPrep is installed and works like a charm, thanks you very much, どうもありがとうございます   :-)

**Comment by yuki-kimoto** [comment]
Good!
