### ISSUE TITLE
The subdirectory name is lost

### ISSUE THREAD

**Issue by sadok** [yuki-kimoto/gitprep#122]
Structure: the file with a MD-markup in a /sub/test.md and the "/sub/images" folder. File contents:

```
Test test test

![Test image] (images/pic.jpg)
```

When I load the project on the server, the link to the picture looks here so:

```
/myname/myproject/raw/master/images/pic.jpg"
```

And shall look here so:

```
/myname/myproject/raw/master/sub/images/pic.jpg"

```

If to transfer all this to a project root, then the link is displayed correctly:

```
/myname/myproject/raw/master/images/pic.jpg"
```

**Comment by yuki-kimoto** [comment]
I will check it.
