### ISSUE TITLE
Removing user creates empty entries in project collaborators

### ISSUE THREAD

**Issue by cybertim** [yuki-kimoto/gitprep#123]
When you add a collaborator to a project, then delete the user, the user is not rmoved from the projects it collaborated on, so you end up with a weird empty entry like this:
![screen shot 2016-11-07 at 11 40 44](https://cloud.githubusercontent.com/assets/5379564/20054945/42d6bd26-a4df-11e6-9b71-1981e592edc7.png)
Clicking remove will not remove the empty entry.

**Comment by troneill** [comment]
Was unable to recreate this. What was the username you removed from collaborators? Any other details you could provide?

**Comment by monnerat** [comment]
This should be OK now, after https://github.com/yuki-kimoto/gitprep/commit/5b059a9465fd36aae06db85625f586e8c7846c1a has landed into master.
Please ty with a new clone and report here, thanks.
