### ISSUE TITLE
Toggle buttons HTTP/SSH are not coloured correctly

### ISSUE THREAD

**Issue by cybertim** [yuki-kimoto/gitprep#124]
When you have SSH selected by default:
![screen shot 2016-11-07 at 11 47 22](https://cloud.githubusercontent.com/assets/5379564/20055143/11d5e5fc-a4e0-11e6-88b8-c2a29c0839a9.png)
Selectinh HTTP does not unselect SSH. but makes HTTP blue:
![screen shot 2016-11-07 at 11 47 08](https://cloud.githubusercontent.com/assets/5379564/20055158/1bf850b0-a4e0-11e6-98c0-18754638c3d3.png)

Also, is it possible to get a config-option to disable the 'SSH' option on this template?
Thank you.

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by monnerat** [comment]
Fixed now: active button blue, other(s) light grey.
