### ISSUE TITLE
Correct way to uninstall gitprep

### ISSUE THREAD

**Issue by anakinksky** [yuki-kimoto/gitprep#129]
For some reasons, I need to uninstall the gitprep on my mac and make new clean install. 
Is there any command I can use to uninstall it?

**Comment by yuki-kimoto** [comment]
You only remove gitprep direcotry if you want to uninstall GitPrep. 

You should save gitprep/data directory. This directory consintains all repository and database.

I recommend

    cd gitprep
    ./gitprep stop
    cd ..
    mv gitprep gitprep.bak

    git clone https://github.com/yuki-kimoto/gitprep.git
    cd gitprep

and you copy all files in gitprep.bak/data to gitprep/data
