### ISSUE TITLE
github sync

### ISSUE THREAD

**Issue by joshp23** [yuki-kimoto/gitprep#132]
does this sync with a github repo for mirroring?

**Comment by yuki-kimoto** [comment]
Your question means that "can GitPrep use to mirror github repositories?"?

**Comment by joshp23** [comment]
yes

**Comment by yuki-kimoto** [comment]
GitPrep have import_rep script to import git repository. This usage is written in FAQ section of README.md

git clone [your github url1]
git clone [your github url2]

and use import_rep script.

If you create shell script, you can mirror GitHub repository.
