### ISSUE TITLE
Wiki UTF-8 support

### ISSUE THREAD

**Issue by nathabonfim59** [yuki-kimoto/gitprep#133]
Is there any configuration for the utf8 character support in the wiki section?

**Comment by yuki-kimoto** [comment]
What do you mean? 

For example "試験" is UTF-8 character, Wiki can display it.
http://perlcodesample.sakura.ne.jp/gitprep/gitprep.cgi/kimoto/gitprep/wiki

**Comment by nathabonfim59** [comment]
I mean some caracteres like: á, é, í, ó, ú
> See [this](https://youtu.be/sQjqgZJ6ugw), for example

**Comment by yuki-kimoto** [comment]
OK, I will check this.

**Comment by yuki-kimoto** [comment]
Fixed.

https://github.com/yuki-kimoto/gitprep/pull/215/commits/8d7acffcedf891dd31ff7bbc5a95edfeaf948275
