### ISSUE TITLE
Unable to install due to build error in Text::Markdown::Hoedown

### ISSUE THREAD

**Issue by Flameborn** [yuki-kimoto/gitprep#134]
Hello,
GitPrep is unable to install via 'setup_module' due to a build error in Text::Markdown::Hoedown. See https://github.com/hoedown/hoedown/issues/216

**Comment by reneeb** [comment]
You should ask https://metacpan.org/author/TOKUHIROM to release a new version of the module. As far as I can see there is already a fix on github : https://github.com/tokuhirom/Text-Markdown-Hoedown/pull/8/commits/67759a3c1dcaa263a71a44e98df3e97954fcf5ff

**Comment by yuki-kimoto** [comment]
This is because Perl 5.26 @INC problem.

https://github.com/tokuhirom/Text-Markdown-Hoedown/issues/7

**Comment by reneeb** [comment]
A new version that contains the fix was released a few hours ago. @Flameborn can you try again to set up GitPrep?

**Comment by Flameborn** [comment]
Unfortunately, I am getting the same error with GitPrep and Hoedown 1.02:

Can't locate builder/MyBuilder.pm in @INC

It seems to build via cpan, to /home/user/perl5 successfully.

**Comment by yuki-kimoto** [comment]
I ask tokuhirom, and new version is uploaded to CPAN now.

**Comment by yuki-kimoto** [comment]
I should fix cpanfile and release new version.

**Comment by yuki-kimoto** [comment]
Can you fix and pull request?

**Comment by Flameborn** [comment]
According to this page http://search.cpan.org/~tokuhirom/ <http://search.cpan.org/~tokuhirom/>, the latest Text-Markdown-Hoedown is 1.02.

My ‘setup_module’ output:

> Working on Text::Markdown::Hoedown
Fetching http://www.cpan.org/authors/id/T/TO/TOKUHIROM/Text-Markdown-Hoedown-1.02.tar.gz ... OK
Configuring Text-Markdown-Hoedown-1.02 ... N/A
! Configure failed for Text-Markdown-Hoedown-1.02. See /home/gp/gitprep/setup/work/1502623244.21051/build.log for details.
! Installing the dependencies failed: Module 'Text::Markdown::Hoedown' is not installed

Build.log output:

Can't locate builder/MyBuilder.pm in @INC (you may need to install the builder::MyBuilder module) (@INC contains: /home/gp/gitprep/extlib/lib/perl5/5.26.0/armv7l-linux-thread-multi /home/gp/gitprep/extlib/lib/perl5/5.26.0 /home/gp/gitprep/extlib/lib/perl5/armv7l-linux-thread-multi /home/gp/gitprep/extlib/lib/perl5 /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at Build.PL line 12.

Unfortunately, the bug is still there.

**Comment by yuki-kimoto** [comment]
I will check Perl 5.26 and install Text::Markdown::Hoedown. Please wait.

**Comment by yuki-kimoto** [comment]
And can you research the reason? Hint is bellow google search result.

https://www.google.co.jp/search?q=Can%27t+locate+builder%2FMyBuilder.pm+in+%40INC+(you+may+need+to+install+the+builder%3A%3AMyBuilder+module)&oq=Can%27t+locate+builder%2FMyBuilder.pm+in+%40INC+(you+may+need+to+install+the+builder%3A%3AMyBuilder+module)&aqs=chrome..69i57.636j0j7&sourceid=chrome&ie=UTF-8

**Comment by yuki-kimoto** [comment]
If this is Perl 5.26 problem, maybe

  export PERL_USE_UNSAFE_INC=1
  setup_module
  
fix this problem.

**Comment by Flameborn** [comment]
This indeed works. If I use 'export PERL_USE_UNSAFE_INC=1’ in Bash, or ‘set -gx PERL_USE_UNSAFE_INC 1’ in Fish, Hoedown installs successfully. Thank you very much!

Should I talk to https://metacpan.org/author/TOKUHIROM <https://metacpan.org/author/TOKUHIROM> about this?

**Comment by yuki-kimoto** [comment]
>Should I talk to https://metacpan.org/author/TOKUHIROM <https://metacpan.org/author/TOKUHIROM> about this?

I think minimal failed case is provided. Maybe normal cpanm install is success, but `cpanm -L extlib Foo` has problem using in setup_module.

If you have some time, it is good to tell me the minimal failed case.

For a while, I add `export PERL_USE_UNSAFE_INC=1` to README.md

**Comment by Flameborn** [comment]
Yes, _cpanm install Text::Markdown::Hoedown_ works. I think Perl considers GitPrep’s Lib directory unsafe.

At any rate, I consider this solved. Thank you very much!

**Comment by bilogic** [comment]
@yuki-kimoto I needed to use `export PERL_USE_UNSAFE_INC=1` in order to work, should we update the readme? I can do it. Thank you.

**Comment by yuki-kimoto** [comment]
Please do it.
