### ISSUE TITLE
A question about migrating

### ISSUE THREAD

**Issue by Isilwing** [yuki-kimoto/gitprep#135]
I have been using gitprep for a while and i love it! thanks guys. I have just a question, if i need to move my installation from server i just backup the gitprep folder, copy it to the new server and what i should do next?

**Comment by yuki-kimoto** [comment]
GitPrep data is only under dada/ directory. the way to move is the following.

1. Install GitPrep to your new server
2. copy your old data directory to your new server. It is OK to overwrite the files of new server.

**Comment by Isilwing** [comment]
Oh thanks for the quick reply Mr. Kimoto!. Nice work you have done on it!

**Comment by yuki-kimoto** [comment]
Let's enjoy!

**Comment by Isilwing** [comment]
Thanks bro! I am enjoying it.
