### ISSUE TITLE
DBD::SQLite::db prepare failed: near ",": syntax error after upgrading to latest Gitprep

### ISSUE THREAD

**Issue by halilibrahim** [yuki-kimoto/gitprep#137]
Hi,
After upgrading to latest version (with git pull origin master), and restarting gitprep; I'm getting below error while trying to browse any project.

> [Mon Aug 21 07:53:33 2017] [debug] Rendering template "/include/header.html.ep"
> [Mon Aug 21 07:53:33 2017] [error] DBD::SQLite::db prepare failed: near ",": syntax error. Following SQL is executed.
>  select , "user"."id" as "user.id" from "project" left join user on project.user = user.row_id where ( "project"."row_id" = ?  )  
> (DBIx::Custom::_create_query) at /home/gitprep/gitprep/script/../lib/Gitprep/Manager.pm line 443.
> 438:   )->value;
> 439:   
> 440:   croak "Original project don't eixsts." unless defined $original_project_row_id;
> 441: 
> 442:   # Original project
> 443:   my $original_project = $dbi->model('project')->select(
> 444:     [
> 445:       {__MY__ => '*'},
> 446:       {user => ['id']}
> 447:     ],
> 448:     where => {

I've inserted below code to header.html.ep just before app->manager->original_project(...
```perl
warn dumper {
  user_id => $user_id,
  project_id => $project_id
};
```
and I've seen below output when I run the server with ./morbo

```
{
  "project_id" => "myjui",
  "user_id" => "kaitek"
}
```

I'll be glad if you can help me to fix it.

**Comment by yuki-kimoto** [comment]
Do you run `setup_database` after GitPrep upgrading?

**Comment by halilibrahim** [comment]
I didn't run setup_database before your comment. I misunderstood documentation and assumed that running setup_database is just needed for fresh installation and upgrading from v1 to v2.

I've run setup_database now and restarted gitprep server. Nothing changed.

**Comment by yuki-kimoto** [comment]
and run `setup_module`.

**Comment by halilibrahim** [comment]
Everything is ok after running setup_module.

Thanks :thumbsup:

**Comment by yuki-kimoto** [comment]
good!
