### ISSUE TITLE
Make GitPrep work on native Windows

### ISSUE THREAD

**Issue by szabgab** [yuki-kimoto/gitprep#14]
e.g. on Strawberry Perl
Then it will be possible to bundle it with DWIM Perl

**Comment by Zero3K** [comment]
Is there any news regarding this?

**Comment by yuki-kimoto** [comment]
I giveup Native Windows Support.

Good choices are maybe cygwin, msys2 or WSL.

**Comment by Zero3K** [comment]
Do you still have the source of the Win branch? If so, please share it so I can give the link to whoever I find.

**Comment by Zero3K** [comment]
Maybe you could open this issue and add a help wanted tab to it so that others can help get it fixed.
