### ISSUE TITLE
Comment buttons don't work

### ISSUE THREAD

**Issue by ersinpw** [yuki-kimoto/gitprep#141]
Comment buttons don't work when you create a new issues (however, it does work when you reply to an issue)
<img width="232" alt="screen shot 2017-10-11 at 20 05 17" src="https://user-images.githubusercontent.com/8781415/31458215-ad373b6a-aebf-11e7-97b1-7aab303d3113.png">

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by monnerat** [comment]
Fixed by commit https://github.com/yuki-kimoto/gitprep/commit/fda0bc2fbd5c5a04a524a19bedd306156e0910eb
