### ISSUE TITLE
can't push by http protocol

### ISSUE THREAD

**Issue by ghost** [yuki-kimoto/gitprep#143]
Installed everything fresh yesterday, Couldn't push "http" so fixed server setting, and git client setting to "1024000000".Now returns
! refs/heads/master:refs/heads/master [remote rejected] (unpacker error)
Done
failed to push some refs to 'http://......git'
'master' rejected (non-fast-forward)
Delta compression using up to 4 threads.
Total 33 (delta 1), reused 0 (delta 0)
remote: fatal: early EOF        
error: remote unpack failed: unpack-objects abnormal exit

Gitprep server/folder setting
Owner:Gitprep
Group:Git
All permissions: Anyone 

Trying to add ssh-rsa key via github method returns /mojo/failraptor.png

**Comment by yuki-kimoto** [comment]
You see the following doument at once? In some reason, HTTP protocol fail.

https://github.com/yuki-kimoto/gitprep#i-cant-push-large-repository-by-http-protocol

**Comment by Zero3K** [comment]
How about making the defaults bigger (if possible)?

**Comment by monnerat** [comment]
> Installed everything fresh yesterday, Couldn't push "http" so fixed server setting, and git client setting to "1024000000".

I suspect the limit increase has not been applied everywhere (git client, Mojolicious, cgi/reverse proxy).
Please check and report details about your configuration here.

> Trying to add ssh-rsa key via github method returns /mojo/failraptor.png

This should work nowadays, unless there are file access permission restrictions. If  the problem persists, enable production log and check the logged error reason.

**Comment by monnerat** [comment]
Issuing user has been deleted. Closing.
