### ISSUE TITLE
"-" in User_ID

### ISSUE THREAD

**Issue by ktrace** [yuki-kimoto/gitprep#144]
I create user (for example) user-may-fail. And create repos (and import into).
```
gitprep@gitprep.site/~/git/user-may-fail/repo1.git
gitprep@gitprep.site/~/git/user-may-fail/repo2.git
gitprep@gitprep.site/~/git/user-may-fail/greatproject.git
```
when i clone via ssh, 

`git clone ssh://gitprep@gitprep.site/~/git/user-may-fail/repo1.git`

error received
`Invalid command: git-upload-pack '~/git/user-may-fail/repo1.git'`

because user_id not checked to "-", but path in commands checked:

`if ($ssh_original_command =~ m(^($git_commands) '.*/([a-zA-Z0-9\-_]+)/([^\/]+?)\.git'$)) {`
in script/gitprep-shell-raw

---
```
81c81
<   if ($ssh_original_command =~ m(^($git_commands) '.*/([a-zA-Z0-9_]+)/([^\/]+?)\.git'$)) {
---
>   if ($ssh_original_command =~ m(^($git_commands) '.*/([a-zA-Z0-9_\-]+)/([^\/]+?)\.git'$)) {
```

**Comment by yuki-kimoto** [comment]
OK. Let's pull request.

**Comment by ktrace** [comment]
OK
