### ISSUE TITLE
Install CGI Gitprep

### ISSUE THREAD

**Issue by push32** [yuki-kimoto/gitprep#147]
Hello

I tried to install gitprep in CGI, and so little documentation to setting the CGI, Error that i'm last tried is 403 Forbidden

FastCGI sent in stderr: "Cannot get script name, are DOCUMENT_ROOT and SCRIPT_NAME (or SCRIPT_FILENAME) set and is the script executable?" while reading response header from upstream

maybe someone can guide to solve this problem

**Comment by yuki-kimoto** [comment]
Do you have 755 permission gitprep.cgi?

**Comment by push32** [comment]
Thank you Mr @yuki-kimoto for the reply

i lost track about installing, maybe i will try from start again

どうもありがとうございます

**Comment by yuki-kimoto** [comment]
Thank you for using GitPrep now. 

I will return back GitPrep development after SPVM 1.0 release.

https://metacpan.org/pod/SPVM

ありがとう。

**Comment by push32** [comment]
Dear Mr Yuki Kimoto,

Success for SPVM Project.. 頑張って

Best Regards,

-- 
Chu En

**Comment by Zero3K** [comment]
Any news regarding this issue?

**Comment by monnerat** [comment]
Closing, according to issuer comment.
