### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by lil5** [yuki-kimoto/gitprep#150]
There is a vague 'license' text in the readme but it doesn't state which GPL license.

https://choosealicense.com/

Might I suggest the AGPL v3 written especially for web programs.

https://choosealicense.com/licenses/agpl-3.0/

**Comment by jeansergegagnon** [comment]
I agree, this is probably important to put in place especially if we want gitprep adopted by bigger companies.

Not sure what license is best, but that depends on @yuki-kimoto 's choice of "free for commercial use" or not as well as "source code can be modified" or "free to fork and re-use in own projects" for example.

Those are all big decisions.

**Comment by lil5** [comment]
MPL 2.0 is a nice middle point of open source and copy left (if your into that)

**Comment by yuki-kimoto** [comment]
I don't understand what licence is good.

```
This program is free software; you can redistribute it and/or modify it
under the same terms as Perl itself.
```

This is used in general Perl modules.

I copy it to GitPrep.

Is this ambiguas?

**Comment by lil5** [comment]
Yes either copy the license file into this github repo named `LICENSE` or add a different one.

Referencing to a different project license is not a good idea.

**Comment by yuki-kimoto** [comment]
I understand Linux is GPL v2.

If I choose GPLv2, what is benefit and demerit?

Tell me benefit and demerit of MPL and AGPL .

**Comment by jeansergegagnon** [comment]
Check this out https://choosealicense.com/

I'd suggest the MIT license if you really want it fully open.

However, if you want to enforce source code being available, you could choose GPLv3.

Keep in mind that having no license means this:
https://choosealicense.com/no-permission/

**Comment by yuki-kimoto** [comment]
I want to select licence as same as git.

Do you know git licence?

**Comment by jeansergegagnon** [comment]
It's LGPL

https://github.com/git/git/blob/master/LGPL-2.1

**Comment by yuki-kimoto** [comment]
After some thinking, I want to choose a license as same as Perl.

Artistic License 2.0

**Comment by stokito** [comment]
Please don't use the Artistic 2. Just use GPLv2 which is best known and used by Linux and Git.

The Artistic is less known and fragmentation of licenses hurts end users who don't have a time or don't know to learn about them.
So they may just choose another software.

The Perl itself dual licensed by the Artistic and GPLv1
https://github.com/Perl/perl5/blob/blead/Copying

Also the artistic is compatible and is suppressed by the GPL
 https://www.gnu.org/licenses/license-list.en.html#ArtisticLicense2

**Comment by yuki-kimoto** [comment]
@stokito 

I've been thinking about licensing for a while.

GitPrep is a web application. 

It is possible to choose GPLv2, which is easy for users to understand and widely accepted by Linux and Git.
