### ISSUE TITLE
Not able to create pull request to branch other than master

### ISSUE THREAD

**Issue by jeansergegagnon** [yuki-kimoto/gitprep#154]
Pull request to develop branch showing "no changes found" even though it shows there are commits not there in the branches view.

Setting destination branch to master, it allows creation of pull request.

Using v2.6.1, here are steps to reproduce:

1. Create repo
2. Create develop branch
3. Change default branch to develop
4. On remote host, create new branch (bug-123-fix-hooks for example)
5. Commit and push change on this new branch
6. In gitprep, go to repo and branches
7. See that there is a commit on the bug-123-fix-hooks branch
8. Click the **New pull request** button
9. It shows:

> There isn't anything to compare.
> develop is up to date with all commits from BUG-123-fix-hooks. Try switching the base for your comparison.

**Comment by yuki-kimoto** [comment]
I don't fix it yet.

**Comment by prashant0085** [comment]
@yuki-kimoto Thanks for the update yuki-san

**Comment by yuki-kimoto** [comment]
Fixed.

https://github.com/yuki-kimoto/gitprep/pull/223/commits/a2480ea4825bfd4af15cf888ebfbd2ccb87502cc
