### ISSUE TITLE
Cannot browse repo with no 'master' branch

### ISSUE THREAD

**Issue by brainchild0** [yuki-kimoto/gitprep#158]
I believe I identified a bug.

**Steps to reproduce:**   It is easy for me to reproduce with the follow steps:

1. Create new repository with default settings.
2. Push branch *not* named '`master`'.  *Do not* push a branch named '`master`'.
3. Navigate browser to repository location.

**Expected behavior:**   Some combination of the  following should occur:

*  Show a branch that does exist, or show a list of all branches, or report an informative error message explaining the specific issue. 
*  Provide an opportunity for the user to navigate to the repository configuration to set a different default branch.
*  Display the repository initialization message providing instructions for pushing branches from the client.

**Actual behavior:**  All of the following occur:

*  Display a generic error message in the browser: "Something went wrong."
*  Block the user from changing the configuration settings for the repository.
*  Report the following text in the *production* log:  
     ~~~
    [TIMESTAMP] [error] Gitprep::Git=HASH(0x415f428)404Reading tree failed at 
    /usr/share/perl5/vendor_perl/Carp.pm line 100.  
    95:     # Icky backwards compatibility wrapper. :-(
    96:     local @CARP_NOT = $cgc ? $cgc->() : caller();
    97:     shortmess_heavy(@_);
    98: }
    99: 
    100: sub croak   { die shortmess @_ }
    101: sub confess { die longmess @_ }
    102: sub carp    { warn shortmess @_ }
    103: sub cluck   { warn longmess @_ }
    104: 
    105: BEGIN {
   ~~~
 
**Affected version:**  aec5159.

**Comment by emil-perhinschi** [comment]
this was fixed in pull request https://github.com/yuki-kimoto/gitprep/pull/190 , I think it can be closed

**Comment by yuki-kimoto** [comment]
Thanks for comments. I decide to close this issue.
