### ISSUE TITLE
Internal error when trying to create a Repository

### ISSUE THREAD

**Issue by Zero3K** [yuki-kimoto/gitprep#166]
When I try to create a Repository using the web interface (running on Windows 7), I get the following error in the production.log along with the mentioned Internal error:

[2020-02-07 20:04:18.74900] [6692] [error] /_new: Can't execute git init --bare:/cygdrive/c/Program Files/Git/cmd/git --git-dir=/home/Bryan/gitprep/script/../data/rep/Zero3K/presto.git init --bare at /home/Bryan/perl5/lib/perl5/DBIx/Connector.pm line 319.

**Comment by Zero3K** [comment]
Its the Manager.pm file in /lib/Gitprep/ that is causing the issue. I hope someone can fix it soon.

**Comment by Zero3K** [comment]
A fix is provided in the attached file:

[git change 20200208.docx](https://github.com/yuki-kimoto/gitprep/files/4174623/git.change.20200208.docx)

**Comment by monnerat** [comment]
Thanks for your fix suggestion but this deviates from the current git documentation.
After 4.5 years, it's hard to know what happened to you at this time.
IMHO, you had a too old git version that did not properly support specifying --git-dir without --work-tree (I found a post about it: https://stackoverflow.com/questions/1386291/git-git-dir-not-working-as-expected). If you still run the same installation, please upgrade git and retry.

**Comment by Zero3K** [comment]
I stopped using it.
