### ISSUE TITLE
Limit number of forked perl processes

### ISSUE THREAD

**Issue by Zero3K** [yuki-kimoto/gitprep#167]
How do I do that? I have 5 perl processes running when running the web server on Windows 7 and would like to reduce that to 2 or 3 perl processes.

**Comment by emil-perhinschi** [comment]
Are you running with Apache ? 5 sounds like the number of workers Apache would start by default.

**Comment by emil-perhinschi** [comment]
Tested, works as expected.

Issue can be closed.

**Comment by yuki-kimoto** [comment]
Thanks.
