### ISSUE TITLE
Encoding error when using http/2

### ISSUE THREAD

**Issue by mazimmer** [yuki-kimoto/gitprep#168]
On Windows clients I have seen encoding errors when trying to interact with GitPrep (installed as CGI, behind Apache 2.4).
The workaround was to force the git client to use http/1.1 instead of http/2:

`git config --global http.version HTTP/1.1 `

**Comment by yuki-kimoto** [comment]
thank you.

Do you hope what I do?

Add this to Document?

**Comment by monnerat** [comment]
Troubleshoting tip added in README.
Thanks for reporting.

**Comment by sskras** [comment]
But this wasn't a fix. It requires changes on maybe thousands of clients.
IMO the issue should be reopened for doing the proper, the server-side fix.
