### ISSUE TITLE
Ssl error

### ISSUE THREAD

**Issue by Isilwing** [yuki-kimoto/gitprep#172]
There is a issue that just pop with v .5 on ssl connection, I guess is the upgrade of the browsers to tls 1.2 the last version have support for it?

**Comment by monnerat** [comment]
I tried today with [9df7c7d](https://github.com/yuki-kimoto/gitprep/commit/9df7c7d763e14fb5d9735f4ec1c54afc8cbf93b7) and Mojolicious 9.34: it works with TLS 1.2 and 1.3.

**Comment by yuki-kimoto** [comment]
I'll close this issue for now. If you encounter any further problems, please feel free to reopen it.
