### ISSUE TITLE
./setup_module syntax error: got (, expecting Newline 

### ISSUE THREAD

**Issue by lbdyck** [yuki-kimoto/gitprep#175]
After doing a git clone tried the ./setup_module and got this:

SPLBD:/u/splbd/work/gitprep/gitprep: >./setup_module                
./setup_module 1: FSUM7332 syntax error: got (, expecting Newline   

Perl is 5.24

Tried again under bash and got this:

/u/splbd/work/gitprep/gitprep>./setup_module                                                                                        
./setup_module: line 1: syntax error near unexpected token `$'^\347''                                                               
./setup_module: line 1: `--ÂÑ>ËÇ-äíê^àñê^ âë---ÄÀ---ÀÑÊ>/_Á------øÏÀ--ÁÌø?ÊÈ-&áê<^ä& +(^ç|(á--äíê^àñê^ âëËÁÈÍø-øÁÊ%-Äø/>_-->--%-ÁÌÈ%
ÑÂ-(?ÀÍ%Á--ä?ÊÁ<ÑËÈ-øÁÊ%--ñÁÌÈ%ÑÂ%ÑÂøÁÊ%--Äø/>_--Ã--<-ÁÌÈ%ÑÂ-áÌÈíÈÑ%Ë--(/,Á(/,ÁÊ-øÁÊ%--ñÁÌÈ%ÑÂ%ÑÂøÁÊ%--Äø/>_--<-ÁÌÈ%ÑÂ---Ñ>ËÈ/%%ÀÁøË
------äÊÁ/ÈÁ-ÅÑÈøÊÁø-ËÇÁ%%-ËÄÊÑøÈ-äíêêá+è^&áê<--ÏÇÑÄÇ-øÁÊ%--ÁÄÇ?----ÂÑ>ËÇ----ËÄÊÑøÈÅÑÈøÊÁø-ËÇÁ%%-ÁÄÇ?-->---äíêêá+è^&áê<--äíê^àñê^ âë
ËÄÊÑøÈÅÑÈøÊÁø-ËÇÁ%%-Ê/Ï-----ËÄÊÑøÈÅÑÈøÊÁø-ËÇÁ%%-ÁÄÇ?----------ËÄÊÑøÈÅÑÈøÊÁø-ËÇÁ%%-ÄÇ_?À-----ËÄÊÑøÈÅÑÈøÊÁø-ËÇÁ%%-'                   
/u/splbd/work/gitprep/gitprep>                                                                                                      

I'm attempting this on IBM's z/OS Unix System Services version 2.4.

**Comment by yuki-kimoto** [comment]
Thank you for this report.

On the other hand, sorry to spare time to fix this.

Maybe, This is encoding problem.

**Comment by monnerat** [comment]
Obviously your setup_module file has been converted to EBCDIC while transfering it to z/OS. I'm not used to this OS, but on IBM i, PASE perl does not like ebcdic files.
The solution to your problem is to make sure gitprep files are ascii or utf-8 encoded. If z/OS features a content-encoding file property (like IBM i does), it must be consistent with the actual file content.

**Comment by yuki-kimoto** [comment]
I'll close this issue for now. If you encounter any further problems, please feel free to reopen it.
