### ISSUE TITLE
Private mode

### ISSUE THREAD

**Issue by bilogic** [yuki-kimoto/gitprep#178]
Hi,

I finally managed to set things up, really nice work! 

Gitprep shows all users and repos without any login. Able to require login before anything is shown? 

I tried creating a private repository, but other users who logged in cannot see them.

My suggestion is to have a mode that hides everything until a user logs in.

Thank you!

**Comment by bilogic** [comment]
I found out it involves adding the following to the top of `templates/auto/index.html.ep`.
How do I make it configurable from `gitprep.conf`? Thank you.

```perl
<%

  # API
  my $api = gitprep_api;

  # Authentication
  unless ($api->logined) {
    $self->redirect_to('/_login');
    return;
  }
...
```

**Comment by yuki-kimoto** [comment]
>How do I make it configurable from gitprep.conf?

Yes. Please create a new option.

> And is there something like a middleware which can affect all HTTP requests instead of going to each HTML template?

In Mojolicious, that is in under method.

https://github.com/yuki-kimoto/gitprep/blob/master/lib/Gitprep.pm#L344

**Comment by bilogic** [comment]
```perl
# Authentication
{
    my $path = $self->req->url->path->parts->[0] || '';
    my $op = $self->param('op') || '';
    my $redirect = 1;

    if ($path eq '_login') {
        $redirect = 0;
    }

    if (lc $self->req->method eq 'post' && $op eq 'login') {
        $redirect = 0;
    }

    if (!$api->logined_admin && $redirect == 1) {
        $self->redirect_to('/_login');
        return;
    }
}
```
I tried above code, but keep getting 302 back to `/_login` URL. 
Any idea why? Thank you.

**Comment by yuki-kimoto** [comment]
> Where can I find example of how to read from conf file?

use config method.

https://github.com/yuki-kimoto/gitprep/blob/master/lib/Gitprep.pm#L637

**Comment by bilogic** [comment]
Ok thanks! 
I'm really having trouble understanding the `under(...)` method, is what I'm trying to do possible? i.e. prevent all pages from being viewed until user logs in.

**Comment by yuki-kimoto** [comment]
> I tried above code, but keep getting 302 back to /_login URL. Any idea why?

For example. In under method.

```
my $hide_all_no_login = $self->config->{basic}{hide_all_no_login};

if ($hide_all_no_login && !$api->logined) {
   $self->redirect_to('/_login');
   return;
}
```

**Comment by bilogic** [comment]
Thanks! Let me try, I will file a PR once it works

**Comment by bilogic** [comment]
> > I tried above code, but keep getting 302 back to /_login URL. Any idea why?
> 
> For example. In under method.
> 
> ```
> my $hide_all_no_login = $self->config->{basic}{hide_all_no_login};
> 
> if ($hide_all_no_login && !$api->logined) {
>    $self->redirect_to('/_login');
>    return;
> }
> ```

Hmm, doesn't work. Based on my testing, `/user1` does not flow through `under()`. No matter, what I wrote, loading `/user1` does not redirect to `/_login`

**Comment by yuki-kimoto** [comment]
Could you push the branch?

**Comment by yuki-kimoto** [comment]
>/user1 does not flow through under()

write the following warnings in under method.

```
warn "AAAAAAAA";
```

Can you get output in stderr?

**Comment by bilogic** [comment]
@yuki-kimoto 

Ok, I'm seeing lines appear in `log/development.log` for all URLs.

Trying to figure out the issue. Thank you.

**Comment by yuki-kimoto** [comment]
OK.

If you have a trouble, you can ask questions!

**Comment by bilogic** [comment]
I think also need to add basic auth for private mode `git clone https://...`.

I found this https://metacpan.org/pod/Mojolicious::Plugin::BasicAuth, but not sure how to read the username/password from database. 

Any idea? Thank you.

**Comment by yuki-kimoto** [comment]
Authentication logic is already exists in GitPrep. Please see the following code at first.

https://github.com/yuki-kimoto/gitprep/blob/master/templates/auto/_login.html.ep#L40

Do you feel Is this not enough?

**Comment by bilogic** [comment]
It's ok now, I did not know `.git` was handled separately. Thank you.
