### ISSUE TITLE
https for clone/push URL

### ISSUE THREAD

**Issue by bilogic** [yuki-kimoto/gitprep#180]
![image](https://user-images.githubusercontent.com/946010/122651136-5f905d80-d169-11eb-868b-c2af63d06712.png)

Where can I modify this to be https? Thank you.

**Comment by yuki-kimoto** [comment]
If the site is https, the part become https automatically.

If you check it in development environment. Do the following.

```
export MOJO_LISTEN=https://*:3000
./morbo
```

**Comment by bilogic** [comment]
> If the site is https, the part become https automatically.
> If you check it in development environment. Do the following.
> ```
> export MOJO_LISTEN=https://*:3000
> ./morbo
> ```

How about production? I'm still getting only http:// only
Mine as follows. Does Gitprep have to be `https`? I'm confused, there is no cert there..

```BASH
# Gitprep.conf

[hypnotoad]
;;; Listen URL (default: http://*:10020)
;listen=http://*:10020


# Apache

    ProxyRequests Off
    ProxyPreserveHost On
    # ProxyPass / http://localhost:3000/
    # ProxyPassReverse / http://localhost:3000/
    ProxyPass / http://localhost:10020/
    ProxyPassReverse / http://localhost:10020/
    RequestHeader set X-Forwarded-Proto https
```

**Comment by bilogic** [comment]
Ok, found the issue, I did not enable `reverse_proxy.on = 1`
