### ISSUE TITLE
Suggested better setup

### ISSUE THREAD

**Issue by bilogic** [yuki-kimoto/gitprep#186]
Hi,

I think these steps will make it easier to install and upgrade:

1. rename `gitprep.conf` as `gitprep.conf.example`
2. remove `/data` folder
3. Installation should start with `git clone https://github.com/yuki-kimoto/gitprep` instead of using `curl`
    ```
    git clone https://github.com/yuki-kimoto/gitprep
    cd gitprep
    ./setup_module
    ```
4. If `gitprep.conf` does not exists, `setup_module` will create it from `gitprep.conf.example`
5. If `/data` folder does not exists, `setup_module` or `setup_database` will create it
6. To upgrade, just do a `git pull` in the gitprep folder (which won't overwrite `gitprep.conf` and `/data`)

Possible?

**Comment by yuki-kimoto** [comment]
OK.

**Comment by yuki-kimoto** [comment]
>If /data folder does not exists, setup_module or setup_database will create it

Are you going to choose setup_module or setup_module?

**Comment by bilogic** [comment]
I haven't look at the code to determine where is the better place.
Actually, why is there a need to breakdown into setup_module and setup_database?

**Comment by yuki-kimoto** [comment]
The reason is that these are different operations.

It is OK that creating the C<setup> script and run C<setup_module> and C<setup_database> in the C<setup> script.

**Comment by bilogic** [comment]
> It is OK that creating the C script and run C<setup_module> and C<setup_database> in the C script.

Yes, I also thought of this, but you are faster haha.

let's call it `setup`

1. Create `gitprep.conf` if not exists
2. Create `/data` if not exists
3. run `setup_module`
4. run `setup_database`

How about that?

**Comment by yuki-kimoto** [comment]
Almost OK.

How about doing the following?

1. run setup_module
2. Create gitprep.conf if not exists
3. run setup_database(Create /data if not exists)

**Comment by bilogic** [comment]
Yes, I'm OK, you are the boss :)

**Comment by yuki-kimoto** [comment]
I can merge this changes if the codes are written.

**Comment by bilogic** [comment]
OK

**Comment by brainchild0** [comment]
Please consider assigning executable permissions to all setup scripts, including `setup` and `setup_config`. Further, please note that the other ones, `setup_database` and `setup_module`, are not executable or readable for all users. Please consider setting permissions mode to `0775`.

---

```
chmod 755 setup setup_config setup_database setup_modules
```

**Comment by monnerat** [comment]
> chmod 755 setup setup_config setup_database setup_module setup_script

Done in 75813b2.
This issue can be closed now.
