### ISSUE TITLE
reset_password=1 does not work unless hide_from_public is set false

### ISSUE THREAD

**Issue by emil-perhinschi** [yuki-kimoto/gitprep#189]
I'm getting redirected to _login no matter what the reset_password value is unless hide_from_public is 0. /reset-password redirects to _login too. 

It is not preventing me using gitprep so I'll look later at it, I'm still doing manual tests.

**Comment by yuki-kimoto** [comment]
Thanks for reporting.

**Comment by emil-perhinschi** [comment]
pull request sent

**Comment by yuki-kimoto** [comment]
Fixed.
