### ISSUE TITLE
Is there supposed to be a `templates_custom` folder?

### ISSUE THREAD

**Issue by bilogic** [yuki-kimoto/gitprep#196]
`Can't load application from file "/var/www/html/gitprep/gitprep/script/gitprep": /home/gitprep/gitprep/templates_custom folder not found or not writable! Giving up ... at /var/www/html/gitprep/gitprep/script/../lib/Gitprep.pm line 138.`

I'm getting this exception with the latest main branch

**Comment by bilogic** [comment]
This folder should be optional, correct?

**Comment by yuki-kimoto** [comment]
> This folder should be optional, correct?

Yes, maybe.

Commit:

https://github.com/yuki-kimoto/gitprep/commit/de1c70877ade53ba54781306522951170b275f24

Place:

https://github.com/yuki-kimoto/gitprep/commit/de1c70877ade53ba54781306522951170b275f24#diff-09ee8377663aa30caa4006aece21588180cf43aeabc91b554ba6d8f4f5147b8dR44

Comment out is maybe needed.

@emil-perhinschi 

Could you fix this?

**Comment by yuki-kimoto** [comment]
I see the following pull request now.

https://github.com/yuki-kimoto/gitprep/pull/197/files#diff-fc6f347931b6d38604c9e13615c83f99928297a8a44576ed70f2efb007511412R44

`custom_template_folder`  is commented out.

**Comment by emil-perhinschi** [comment]
... yes, should have been commented out

**Comment by yuki-kimoto** [comment]
Thank you for your reply.

> ... yes, should have been commented out

OK.

**Comment by emil-perhinschi** [comment]
sorry to have replied so late, unexpectedly started a new contract in December, did not look at github much since then 

thanks for writing and sharing gitprep, I uploaded 25 personal repos to my instance, it was up since November on a VM with little memory and occasional pushes and pulls happened and found no new problems
