### ISSUE TITLE
Questions about time/timezone

### ISSUE THREAD

**Issue by monnerat** [yuki-kimoto/gitprep#214]
Hi Yuki,
If you agree, I plan to apply some radical changes to time handling in gitprep but before that, I have some questions about it.

#### Time::Moment
I have seen it's only used to get the epoch.
I guess it is used to be sure we deal with a Jan 1 1970 epoch whatever the system OS is, right ?
In that case, we have potential bugs since the perl time function (https://perldoc.perl.org/functions/time) is still called (from Git.pm and issue.html.ep).
If we don't care about non-Unix epoch systems, we could get rid of this module. Else generalize its use.

#### Timezone vs time offset
In the config file, you can enter a time offset (that you call timezone), but this may be inaccurate since it does not respect the daylight saving time periods for your real timezone (i.e. Asia/Tokyo). I propose to convert gitprep to use real timezones. Your opinion ?

#### Reference timezone
We can consider 3 timezones: commit timezone, browser/user time and server timezone.
By now, gitprep uses the server timezone, which is the least significant of the 3 for the users.
Migrating to use the commit timezone is not very handly for users as different commits may have different timezones. I addition, they are offsets, not zones.
A user timezone seems the most appropriate.
What do you think about it ?

#### Possible handling of a user timezone
This might be a user configurable parameter in gitprep's database. However what about anonymous users ?
Client browser timezone may be the solution.
But now the problem is to get it in the server **before** the page is composed: there's nothing in the HTTP headers that we can use for that and ajax can't help us much since the page is already displayed when ajax is activated.
An alternative approach is to let javascript convert timestamps to dates/times in the client browser and handle it in gitprep in an agnostic way. This is my preferred solution. And yours ?

Thanks in advance for your "brainstorming results" about it !

**Comment by yuki-kimoto** [comment]
You can get rid of Time::Moment to fix potential bugs.

**Comment by yuki-kimoto** [comment]
**Timezone vs time offset**

>I propose to convert gitprep to use real timezones.

OK. Timezone is better.

**Comment by yuki-kimoto** [comment]
**Reference timezone**

A browser/user time timezone is the most appropriate.

**Comment by yuki-kimoto** [comment]
**Possible handling of a user timezone**

An alternative approach is to let javascript convert timestamps to dates/times in the client browser and handle it in gitprep in an agnostic way. This is my preferred solution. And yours ?

It looks like good.

**Comment by monnerat** [comment]
Thank you for your answers. I'm glad we're on the same wave length :-)
