### ISSUE TITLE
Suggestion: use a stronger hash for user passwords

### ISSUE THREAD

**Issue by kanatohodets** [yuki-kimoto/gitprep#50]
First - gitprep looks really neat! 

However, it may be a good security idea to hash passwords with a more difficult hash function than md5 (even 2x MD5 with a salt :). https://github.com/yuki-kimoto/gitprep/blob/9a489027b13d805d61133dd8b3d22cfb155f1864/lib/Gitprep/API.pm#L15 is where I'm referring to. 

https://metacpan.org/pod/Mojolicious::Plugin::Bcrypt might be a good option here, but I'm not sure if it will work with the version of mojo gitprep ships with.

**Comment by yuki-kimoto** [comment]
To understand this discussion, I should learn more security. I close this issue at once.
