### ISSUE TITLE
Adding SSH Key Yields a Pink Box that says Internal Error

### ISSUE THREAD

**Issue by jeffmikels** [yuki-kimoto/gitprep#64]
I'm attempting to add an SSH key to my user account, and all it does is reply with a pink box that says Internal Error. Please help me track down the real error.

**Comment by frizkey** [comment]
create .ssh folder in home directory.

**Comment by vdcrea** [comment]
Same issue for me, I have created the .ssh folder at the root of my access path (on a shared server). Tried to check the real path to .ssh with `pwd` and set up in `gitprep.conf`, stopped and restarted ./gitprep. But adding a ssh key to the account still show up the Internal error alert.

Do I need to had .ssh inside /gitprep/data/rep/user ?
Error log is almost the same as above
```
[Wed Oct 26 23:12:47 2016] [warn] Config "authorized_keys_file" can't be detected
[Wed Oct 26 23:12:50 2016] [warn] Config "authorized_keys_file" can't be detected
[Wed Oct 26 23:22:34 2016] [warn] Config "authorized_keys_file" can't be detected
[Wed Oct 26 23:22:35 2016] [error] /gitprep.cgi/vdcrea/_settings/ssh:authorized_keys file "" is not found. at template /user-settings/ssh.html.ep line 114.
161:     # Icky backwards compatibility wrapper. :-(
162:     local @CARP_NOT = $cgc ? $cgc->() : caller();
163:     shortmess_heavy(@_);
164: }
165: 
166: sub croak   { die shortmess @_ }
167: sub confess { die longmess @_ }
168: sub carp    { warn shortmess @_ }
169: sub cluck   { warn longmess @_ }
170: 
171: BEGIN {
```

**Comment by yuki-kimoto** [comment]
I don't try CGI environment in SSH public authentication.

I will try it at once.

**Comment by vdcrea** [comment]
I added the key manually (not using the gitPrep UI).

`cat ~/.ssh/id_rsa.pub | ssh sharedhostingusername@sharedhostinghost "mkdir -p ~/.ssh && cat >>  ~/.ssh/authorized_keys"`

It worked for me.

**Comment by yuki-kimoto** [comment]
OK. 

As @frizkey say, .ssh directory is maybe needed in home direcotry.
