### ISSUE TITLE
Good! only 2 moments..

### ISSUE THREAD

**Issue by Den68** [yuki-kimoto/gitprep#67]
else gitprep for reverse proxy, ip address is 127.0.0.1:9000 - is not access in world.
in project-repository link instesd: http://127.0.0.1:9889/Petro/phpaaa.git - no good ...
and question 2: autorizate api ? from existen cooke from domen .. or another method, conect to mysql base and read, or api function send login/pasword and recive true or false ...

**Comment by yuki-kimoto** [comment]
I decide I don't add POST API to GitPrep.
