### ISSUE TITLE
Can not push new repo via SSH

### ISSUE THREAD

**Issue by RaD** [yuki-kimoto/gitprep#71]
There is an error while I try to upload new repo on fresh installed GitPrep:

    $ git push -v -u origin master
    Pushing to ssh://gitprep@djbook.ru/rad/uv-timer.git
    Enter passphrase for key '/home/rad/.ssh/id_dsa': 
    Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.

HTTP pushing works well. My SSH keys pair is good and used for a long time. What should I check to fix this error?

Also I think you need to add a command `mkdir ~/.ssh` to the README file. This helps to avoid the following error:

    [Fri Jan 16 12:57:23 2015] [error] /rad/_settings/ssh:Can't create authorized_keys file: /home/gitprep
/.ssh/authorized_keys at template /user-settings/ssh.html.ep line 90.

**Comment by eboye** [comment]
Thanks for the tip for creating ~/.ssh

I had no idea what is going on until I looked at the log file :D

**Comment by RaD** [comment]
What path should I check to obtain that log file?

**Comment by RaD** [comment]
/var/log/auth.log

    Feb 25 03:11:44 gitprep sshd[24988]: error: Could not load host key: /etc/ssh/ssh_host_HASH_key
    Feb 25 03:11:44 gitprep sshd[24988]: Invalid user git from IPADDRESS
    Feb 25 03:11:44 gitprep sshd[24988]: input_userauth_request: invalid user git [preauth]
    Feb 25 03:11:48 gitprep sshd[24988]: Connection closed by IPADDRESS [preauth]

**Comment by RaD** [comment]
Git user was used because of I make a copy from github remote string.
Then I change remote string to:

    url = gitprep@gitprep...

and strike `push` again:

    Feb 25 03:18:47 gitprep sshd[25178]: User gitprep from IPADDRESS not allowed because not listed in AllowUsers

Ok, add gitprep to AllowUsers at `/etc/ssh/sshd_config` and make `restart ssh` then repeat `push`ing:

    Feb 25 03:19:59 gitprep sshd[25204]: Accepted publickey for gitprep from IPADDRESS port PORT ssh2: DSA HASH_HERE
    Feb 25 03:19:59 gitprep sshd[25204]: pam_unix(sshd:session): session opened for user gitprep by (uid=0)
    Feb 25 03:20:00 gitprep sshd[25252]: Received disconnect from IPADDRESS: 11: disconnected by user
    Feb 25 03:20:00 gitprep sshd[25204]: pam_unix(sshd:session): session closed for user gitprep

Then I decide to look at URL string at site page and with following settings I feel good now:

    url = ssh://gitprep@repository.ru/rad/mega_project.git

Thanks for the great product!
