### ISSUE TITLE
Correct base url for apache proxy

### ISSUE THREAD

**Issue by Bravo13** [yuki-kimoto/gitprep#72]
If I use gitprep behind Apache, project URL looks like http://localhost:10020/user/project.git It's would be great that I can set host for project url. For now I just set in project.html.ep 
` var http_rep_url = '<%= url_for("$user/$project.git")->scheme("http")->host("git.myhost")->to_abs %>';`
But may be there are better way?

**Comment by yuki-kimoto** [comment]
It is good to use apache virtual host feature.

Please see section "How to use reverse proxy?" in document.

And you must get domain name such as "somehost.com".

**Comment by Bravo13** [comment]
I'm already use apache virtualhost, uncomment in config 
`[reverse_proxy]                                                                                                             
;;; Reverse proxy support (default:0)                                                                     
on=1 `
in apache conf
`<VirtualHost *:80>
DocumentRoot"/var/www/gitprep/gitprep"
ServerName git.myhost
ErrorLog /var/www/gitprep/gitprep/log/error.log
LogLevel debug
TransferLog /var/www/gitprep/gitprep/log/access.log
<Proxy *>
Order allow,deny
Allow from all
</Proxy>
ProxyPass / http://localhost:10020/ keepalive=On
ProxyPassReverse / http://localhost:10020/
<Directory "/var/www/gitprep/gitprep">
allow from all
Options None
</Directory>
</VirtualHost>`
And still have url for project as http://localhost:10020/user/project.git but http://git.myhost/user/project.git wanted

**Comment by yuki-kimoto** [comment]
Please set to the following config. Don't need DoumentRoot and Directory directive and ErrorLog, LogLevel, TransferLog.

    # HTTP
    <VirtualHost *:80>

      ServerName git.myhost # this is domain name you get domain name service.
      <Proxy *>
        Order deny,allow
        Allow from all
      </Proxy>

      ProxyRequests Off
      ProxyPreserveHost On
      ProxyPass / http://localhost:10020/ keepalive=On
      ProxyPassReverse / http://localhost:10020/
      RequestHeader set X-Forwarded-HTTPS "0"

    </VirtualHost>

You must set DNS setting, domain name and IP address corresponding.
And you must access http://git.myhost, not http://localhost:10020.

**Comment by Bravo13** [comment]
Thx, works great!
