### ISSUE TITLE
Non-english file names

### ISSUE THREAD

**Issue by TitovLab** [yuki-kimoto/gitprep#74]
GitPrep is very nice, thank you!
There is problem with non-english file names.
On commits tab file names displayed incorrectly (on files tab all names fine) and changes not displayed:
![image](https://cloud.githubusercontent.com/assets/11898568/7524505/2be18f0e-f50b-11e4-9d3b-8d6e30c2a929.png)
And files with non-english names can not be viewed as raw (web-browsers show blank page).
OS: CentOS 6.6, GitPrep running as web server on 10020 port. Also tried as Apache CGI - same errors.
Have a nice day!

**Comment by yuki-kimoto** [comment]
@TitovLab

Please set "Guess encoding" project settings page, and tell me the result.
