### ISSUE TITLE
Github quits after a while

### ISSUE THREAD

**Issue by signaleleven** [yuki-kimoto/gitprep#76]
Ohayo Yuki-san,

After launching github, I find it to be not running after some time.
In log/production.log I see this
```
   [Sun May 24 15:52:26 2015] [info] Listening at "http://*:10020".
   [Sun May 24 15:52:26 2015] [info] Manager 16460 started.
   [Sun May 24 15:52:26 2015] [info] Creating process id file "/home/signaleleven/gitprep/script/hypnotoad.pid".
   [Sun May 24 18:52:26 2015] [info] Creating process id file "/home/signaleleven/gitprep/script/hypnotoad.pid".
```
If I restart it, it just does the same. 
What is that other invocation of hypnotoad after 3 hours? (it's always exactly after three hours)

Thanks!
Mike

**Comment by yuki-kimoto** [comment]
Hello, @signaleleven 

>After launching github, I find it to be not running after some time.

Dose this means gitprep stop after some time?

>What is that other invocation of hypnotoad after 3 hours? (it's always exactly after three hours)

hypnotoad don't restart after three hour. 

Your system application kill gitprep after three hour?

**Comment by signaleleven** [comment]
> Dose this means gitprep stop after some time?

Yes.

> hypnotoad don't restart after three hour.
> Your system application kill gitprep after three hour?

I don't know. All I know is what i see in production log.

**Comment by yuki-kimoto** [comment]
Sorry,
I don't know the reason GitPrep stop.

Please tell me your environment information.(Hosting service, OS, perl version, GitPrep version).

**Comment by signaleleven** [comment]
Sorry, I found out the reason, and it was of course my fault.

I run gitprep from my home directory, which is encrypted with encryptfs...and when I log out (or auto logout) gitprep cannot work anymore. Nor writing the log :)

すみません!

**Comment by yuki-kimoto** [comment]
It is good to find the reason!
