### ISSUE TITLE
An image is linked in README should be visible on a first page of repository

### ISSUE THREAD

**Issue by RaD** [yuki-kimoto/gitprep#78]
Hello.

How can I link an image, that is commitied in a repo, to allow it to be visible on a main page of a repository as GitHub do?

I have the image in a root of my repository. I have added `![Изготовленная плата](board.jpg "Плата от DirtyPCBs.com")` in `README.md` but see no image. In HTML I see:

    <p><img src="board.jpg" alt="Изготовленная плата" title="Плата от DirtyPCBs.com"></p>

**Comment by yuki-kimoto** [comment]
Relative path is not supported now. I will add this to wish list.

**Comment by yuki-kimoto** [comment]
This feature is supported at GitPrep 1.11

**Comment by RaD** [comment]
Hmm, just now I have downloading master.zip and update my gitprep instance. There is no image in README section of repository page. But the image exists on README page, i.e. when I click on README file, I will see the image. But I was talking about image on main page of repository.

![2015-11-10 16 19 41](https://cloud.githubusercontent.com/assets/119226/11063329/e09b23b2-87c6-11e5-98f0-76510b8b9440.png)

**Comment by yuki-kimoto** [comment]
Please tell me README.md source code and your repository tree(only top).

**Comment by yuki-kimoto** [comment]
Sorry, I fixed this problem latest master.
