### ISSUE TITLE
import_rep script does not work

### ISSUE THREAD

**Issue by wbiker** [yuki-kimoto/gitprep#79]
Hi,

thanks for this usefull tool.
Unfortunately, I cannot import already existing repos:

I just upgraded my fed 21 to 22. Afterwards gitprep did not longer works.
I copied the content of ./data/rep/wolf to another (/tmp/rep/wolf) folder. Then I removed the gitprep directory and installed it new (curl ...; ./setup.sh ...).
Everything is fine except when I try to import the repos back:

->./script/import_rep -u wolf /tmp/rep/wolf/
Can't creat repository admin_scripts: Can't execute git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git init --bare at /home/gitprep/gitprep/script/../extlib/lib/perl5/DBIx/Connector.pm line 315.
 at /home/gitprep/gitprep/script/../extlib/lib/perl5/DBIx/Connector.pm line 315.
 at ./script/import_rep line 62.

Can't update description admin_scripts
fatal: '/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Did I something wrong?

**Comment by yuki-kimoto** [comment]
Did you create user "wolf" before executing import_rep script?

**Comment by wbiker** [comment]
Hi,

Yes I created the user before.

**Comment by yuki-kimoto** [comment]
Please run the following command.

    git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git

**Comment by wbiker** [comment]
Thanks for your help.
It might be important. I use Fedora 22 (fedup from 21). Git version: 2.4.3

I tried to run the command above. But git reports error:
git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git
error: unknown option `bare:/bin/git'

git init --bare --git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git
error: unknown option `git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git'

git init /home/gitprep/gitprep/data/rep/wolf/admin_scripts.git
works, but import_rep.pl still failes because admin_scripts.git already exists.

greetings

**Comment by yuki-kimoto** [comment]
Don't create admin_scripts.git repository.

If repository is already exists, import_rep fail.

**Comment by wbiker** [comment]
I removed the directory but still the errors. A problem with the linux permissions?

**Comment by yuki-kimoto** [comment]
You should remove admin_scripts.git from GitPrep Web browser. SQLite database yet have admin_scripts.git information.

I recommend setup from first.

1. Install GitPrep
2. create user "wolf"
3. run import_rep script

**Comment by wbiker** [comment]
Thanks for your help. But I had other stuff to do and forget completely :-( In the mean time the tmp folder was emptied and all git repositories are gone.
Not much of a problem, because I have still the git repositories on my drive. However, if I try to create a new repository in the GitPrep User page I got an internal error and the log file looks like:
cat log/production.log
[Mon Oct 12 08:03:02 2015] [info] Listening at "http://*:10020".
[Mon Oct 12 08:03:02 2015] [info] Manager 24981 started.
[Mon Oct 12 08:03:02 2015] [info] Creating process id file "/home/gitprep/gitprep/script/hypnotoad.pid".
[Mon Oct 12 08:06:46 2015] [error] /_new: Can't execute git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git init --bare at extlib/lib/perl5/DBIx/Connector.pm line 315.
[Mon Oct 12 08:06:50 2015] [error] /_new: Can't execute git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/admin_scripts.git init --bare at extlib/lib/perl5/DBIx/Connector.pm line 315.
[Mon Oct 12 08:07:15 2015] [error] /_new: Can't execute git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/adminscripts.git init --bare at extlib/lib/perl5/DBIx/Connector.pm line 315.
[Mon Oct 12 08:07:35 2015] [error] /_new: Can't execute git init --bare:/bin/git --git-dir=/home/gitprep/gitprep/data/rep/wolf/adminscripts.git init --bare at extlib/lib/perl5/DBIx/Connector.pm line 315.

08:10 gitprep@backupbox ~/gitprep
->git --version
git version 2.4.3

Because "git init --bare" is involved I think that problem is connected to the import_script problem.
Do you have a idea? Something with the git version?

Thx

**Comment by toshi-ara** [comment]
I had the same issue but have resolved.
- success: git-1.9.3
- failure: git-2.2.2 and git-2.7.5

**Comment by wbiker** [comment]
argl. That means I stick with that until Fedora updates Git to a working version?
And do git has this problem from version 1.9.3 on?

**Comment by toshi-ara** [comment]
> That means I stick with that until Fedora updates Git to a working version?

I installed git(-1.9.3) from source code into my rental server
 and configured gitprep.conf as

    ;;; Git command path
    ;;; By default, git command path is automatically detected
    ;;; from PATH enviroment variable or /usr/bin/git or /usr/local/bin/git
    git_bin=(path to git in server)/git

> And do git has this problem from version 1.9.3 on? 

I failed using git version 2, but can't know the reason.

**Comment by wbiker** [comment]
THX toshi-ara!

**Comment by wbiker** [comment]
With git 1.9.3 the --bare error is gone. unfortunately, a new one appears:
[Mon Oct 12 15:34:18 2015] [info] Upgrade successful, stopping 24981.
[Mon Oct 12 15:34:21 2015] [info] Creating process id file "/home/gitprep/gitprep/script/hypnotoad.pid".
[Mon Oct 12 15:34:49 2015] [error] /_new: Can't move post-update at extlib/lib/perl5/DBIx/Connector.pm line 315.
[Mon Oct 12 15:35:38 2015] [error] /_new: Can't move post-update at extlib/lib/perl5/DBIx/Connector.pm line 315.
[Mon Oct 12 15:35:42 2015] [error] /_new: Can't move post-update at extlib/lib/perl5/DBIx/Connector.pm line 315.
Every time I want to create a new repository I got the Can't move... error

**Comment by yuki-kimoto** [comment]
I will try git 2 support.

**Comment by yuki-kimoto** [comment]
I maybe support git 2. please try.

**Comment by wbiker** [comment]
THX. Next week I am back at work and will try it again

**Comment by wbiker** [comment]
Hi Yuki-komoto,

I installed current version and with git 2 it works like a charm.

Tanks a lot
