### ISSUE TITLE
can't execute git init

### ISSUE THREAD

**Issue by ssflying** [yuki-kimoto/gitprep#81]
newly installed gitprep with following commands:
1. git clone 
2. setup.sh
3. cp gitprep.conf gitprep.my.conf 
4. change "listen" in gitprep.my.conf

system perl version: 5.10.1

then setup admin password, and add one user.
when using this user to create new repo(WITHOUT Readme checked)
return a 500 system error with the following error log:

    [Wed Oct 28 17:06:08 2015] [error] /_new: Can't execute git init --bare:/usr/local/bin/git --git-dir=/data/home/gitprep/gitprep/data/rep/alick/test.git init --bare at extlib/lib/perl5/DBIx/Connector.pm line 315

I'm running gitprep in server mode, using gitprep username with $HOME directory in /data/home/gitprep.  

git --version is latest 2.6.2

when I run `/usr/local/bin/git --git-dir=/data/home/gitprep/gitprep/data/rep/alick/test.git init --bare` manually, it succeeded.

**Comment by ssflying** [comment]
Hmm...
after I downgrade git from 2.6.2 (build from source) to 1.7.1 (via `yum install git` under Centos 6.2)
this issue disappeard...

**Comment by yuki-kimoto** [comment]
GitPrep don't work git 2 now. I start to support git 2 from tomorrow. Please wait for a while

**Comment by yuki-kimoto** [comment]
I  maybe support git 2 at master. Please try.
