### ISSUE TITLE
GitPrep's primary repo is stored on GitHub

### ISSUE THREAD

**Issue by daveloyall** [yuki-kimoto/gitprep#84]
If GitPrep wants my serious attention, it must "eat its own dogfood" by hosting its own primary source code repository.

**Comment by yuki-kimoto** [comment]
What do you mean? I don't understant what you want to say.

I host GitPrep source code as a example.

http://perlcodesample.sakura.ne.jp/gitprep/gitprep.cgi/kimoto/gitprep

**Comment by daveloyall** [comment]
OK, great!

Please consider changing the link named "Repository & Documentation" on right-hand side at the top of http://gitprep.yukikimoto.com/ to point at this example repository.

Please consider adding commits from https://github.com/yuki-kimoto/gitprep/ to the example repository.  (The last commit there was from 2013.)

Cheers and good luck!

**Comment by daveloyall** [comment]
Also, the phrase about dog food is described here: https://en.wikipedia.org/wiki/Eating_your_own_dog_food

**Comment by yuki-kimoto** [comment]
I update GitPrep repository and add some description to example.
