### ISSUE TITLE
Wiki and Bug Tracking (Add external link)

### ISSUE THREAD

**Issue by cyberlink1** [yuki-kimoto/gitprep#85]
It would be nice to have a simple way to link it to a wiki and a bug tracking/ticketing system

For example most will accept a page name on the URI.

http://sitename.com/wiki?page={repo}

*This is a bugzilla example*
http://sitename.com/product={repo}&resolution=--- 

Where {repo} is the name of the git repo

Maybe have an option in the config to identify the link to the wiki and link to the ticketing system, then if they are set to add a point to the menu after tag

**Comment by yuki-kimoto** [comment]
cyberlink1

I am planning to support external site link such as a wiki or a bug tracking system in repository settings page.

**Comment by cyberlink1** [comment]
Thank you very much, I look forward to seeing the option.

**Comment by yuki-kimoto** [comment]
@cyberlink1 

I add website URL settings.
You can create external link.
