### ISSUE TITLE
autoconf

### ISSUE THREAD

**Issue by oetiker** [yuki-kimoto/gitprep#90]
Hi

Love you GitPrep project. Thank you very much. I just read through the instructions for seting up gitprep ... I guess you could profit from an autoconf setup. If you like, I can restructure gitprep and provide configure make install support including a mini cpan with all the modules required for building ... 

Something like: https://github.com/oetiker/AcmeFetch ... 

cheers
tobi

**Comment by yuki-kimoto2** [comment]
oetiker

I see AcmeFetch.

I don't know the way to write autoconf.

My Question:

1. How to create mini cpan?
2. Is mini cpan size too big?
3. I want for user to select new installation or upgrading of database. Can you resolve this?
4. I will support image uploading(Imager) and sendmail(MIME::Lite). Can you config this setting by autoconf?

I think now It is good to try "make install".

**Comment by yuki-kimoto** [comment]
oetiker

I see AcmeFetch.

I don't know the way to write autoconf.

My Question:

How to create mini cpan?
Is mini cpan size too big?
I want for user to select new installation or upgrading of database. Can you resolve this?
I will support image uploading(Imager) and sendmail(MIME::Lite). Can you config this setting by autoconf?
I think now It is good to try "make install".

**Comment by oetiker** [comment]
I am offering to create a patch witch brings autoconf to gitprep :)

As for the problem with upgrading and installing a new database, I would suggest to try and make this automatic ... I use the system from Mojo::Pg quite a lot, this works great ... and there are even ports for sqlite AND mysql ...

**Comment by yuki-kimoto** [comment]
oetiker

> I am offering to create a patch witch brings autoconf to gitprep

OK. I understand this. I want to offer autoconf patch.

FAQ is the list that I afraid.

Currently, The modules GitPrep need is installed from CPAN by using cpanm and cpanfile. If mini cpan is used. I afraid GitPrep archive size is bigger and the management cost of mini cpan itself is increased.

**Comment by oetiker** [comment]
The reason for distributing the non-core modules in the release archive, is that this allows to build gitprep without direct internet access which is an important feature for many sites.

My intention is to make gitprep more accessible to people who are outside the perl world.

Let me know if you would like to have such a patch.

I will create the patch for you.

**Comment by yuki-kimoto** [comment]
>The reason for distributing the non-core modules in the release archive, is that this allows to build gitprep without direct internet access which is an important feature for many sites.

I think good reason.
I want to offer the patch.

**Comment by oetiker** [comment]
ok ... will create a pull request ... it may take a few days :)

**Comment by yuki-kimoto** [comment]
I close this issue now.
