### ISSUE TITLE
Feature Request: Ability to increase default session expiration period

### ISSUE THREAD

**Issue by kopytov** [yuki-kimoto/gitprep#93]
It's very annoying to have to relogin to GitPrep every hour.

**Comment by yuki-kimoto** [comment]
OK. I will increase default session time and delete save check box.

**Comment by yuki-kimoto** [comment]
I just increase default login session time to 2 weeks.

OK?

**Comment by kopytov** [comment]
Thanks!

**Comment by yuki-kimoto** [comment]
If you find other annoying things, please write about it.

**Comment by kopytov** [comment]
Hi Yuki. It is probably not fixed. After signing into Gitprep I get cookie `mojolicious` which expires after one hour. Please check.

**Comment by yuki-kimoto** [comment]
I'm wrong. I fixed it now.

    # old
    session(expire => time + 60 * 60 * 24 * 14);
    
    # new
    session(expiration => 60 * 60 * 24 * 14);

**Comment by kopytov** [comment]
Thanks! It's OK now.
