### ISSUE TITLE
admin user can't edit/add new users or change the new @gitprep.example

### ISSUE THREAD

**Issue by cybertim** [yuki-kimoto/gitprep#94]
Thanks for the great application, i'm using it for years now.

In the recent version (2.1-dev) when you login as an admin there is no edit screen anymore for new users.
Also, all users suddenly have @gitprep.example as email address, and there is no way of changing this.
And the README.md lacks the information about the admin user / first time login to create users.

**Comment by yuki-kimoto** [comment]
Please wait. I am checking it now.

**Comment by yuki-kimoto** [comment]
In GitPrep 2.0, user must have email address, and default email address is [user id]@gitprep.example.

I can edit this from Users page which URL is "/_admin/users" page.

Please tell me more detail you see when you login as admin.

**Comment by cybertim** [comment]
Yes, I tried it again today, and you are correct, if I visit `/_admin/users` the `Users` option is there.
But there is a link/flow issue, if I click on the top right link `admin` I go to `/admin/` and that is an empty page. There is no way of going to the main menu after leaving the page. Maybe add a `admin console` button in the top right corner when logged in as the Admin?

**Comment by yuki-kimoto** [comment]
OK. I will create the link to admin page.
