### ISSUE TITLE
how to add a gitprep user

### ISSUE THREAD

**Issue by darkz1984** [yuki-kimoto/gitprep#98]
We use gitprep in our company ,but no web interface to add a gitprep user.
how to add a user,and can you add a web interface to add user?

**Comment by takumaniihara** [comment]
Sign in with admin account.
You can add user there.

**Comment by darkz1984** [comment]
but I don't know the admin pass

**Comment by darkz1984** [comment]
Is there a default password for the admin account?

**Comment by yuki-kimoto** [comment]
you set admin password at first time "_start" page.
If you forgot admin password , you can change the following way.

open gitprep.conf. You can see the following lines.

    [admin]
    ;;; If you forget admin password,
    ;;; set this value to 1 and access /reset-password page.
    ;;; Forget to comment out after resetting password.
    ;reset_password=1

**Comment by darkz1984** [comment]
@yuki-kimoto  This action means  I must restart the gitprep service?

**Comment by yuki-kimoto** [comment]
Yes.

**Comment by darkz1984** [comment]
I update sqlite database and set my user as administrator,So I can login by my user and create users...
