### ISSUE TITLE
gitprep can't show markdown tables

### ISSUE THREAD

**Issue by darkz1984** [yuki-kimoto/gitprep#99]
why gitprep can't show markdown table when read markdown file in gitprep webpage? Or is there some settings?

**Comment by takumaniihara** [comment]
Because markdown doesn't support table.
https://daringfireball.net/projects/markdown/syntax

**Comment by yuki-kimoto** [comment]
Tell me more detail. What is markdown table?

**Comment by darkz1984** [comment]
Markdown | Less | Pretty
--- | --- | ---
*Still* | `renders` | **nicely**
1 | 2 | 3
like this.
a document link:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#tables

**Comment by yuki-kimoto** [comment]
table is not spec of markdown. This is spec of GMF. If we support table in GitPrep, we must use the module which support GMF.

I find today.

https://metacpan.org/release/Markdent

This is maybe suitable module.

**Comment by yuki-kimoto** [comment]
Or we can simply implement table parser.

**Comment by yuki-kimoto** [comment]
I support markdown table at master. I add option.

https://github.com/tokuhirom/Text-Markdown-Hoedown

HOEDOWN_EXT_TABLES

but, I don't try table syntax. Please try it.

**Comment by darkz1984** [comment]
Goods news，I will upgrade my code later

**Comment by darkz1984** [comment]
@yuki-kimoto  I try to upgrade to version 2.3,the table is show! Thank you very much.I think this issue could close.
